codecov:
  token: fd44d4ef-bfa6-4257-a3fe-2703db072f37
  require_ci_to_pass: false
  
coverage:
  status:
    project:
      default:
        informational: true
    patch:
        default:
          informational: true
          
