version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests and coverage
          command: |
            pip install coverage
            coverage run -m pytest
            coverage xml
      - run:
          
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash | bash -s -- -t fd44d4ef-bfa6-4257-a3fe-2703db072f37)
workflows:
  
  build:
    jobs:
      - build
