version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run:
          name: Upload coverage reports to Codecov
          command: |
            curl -s https://codecov.io/bash | bash -s -- -t fd44d4ef-bfa6-4257-a3fe-2703db072f37

workflows:
  build_and_test:
    jobs:
      - build
