version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests and coverage
          command: |
            pip install coverage
            coverage run -m pytest
            coverage xml
      - run:
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash)
workflows:
  build:
    jobs:
        name: "Say hello"
        command: "echo Hello, World!"
      - build
