name: CI

on:
  push:
    branches:
      - sprint3
  pull_request:
    branches:
      - sprint3

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # Here, replace 14.x with 18.x

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Set up npm version
      run: npm install -g npm@7

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./Appointmate-software-design/Appointment-booking-system/sprint3/coverage/lcov.info

